[project]
authors = ["josh <joshuaholman5@gmail.com>"]
channels = ["conda-forge"]
name = "diamondhacks"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
requests = ">=2.32.3,<3"
fastapi = ">=0.115.12,<0.116"
uvicorn = ">=0.34.0,<0.35"
nodejs = ">=22.13.0,<22.14"

[pypi-dependencies]
spa = ">=0.10.1, <0.11"
